---
- hosts: jenkins
  become: yes
  tasks:
    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install jdk-11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present